#%RAML 0.8
title: synapseStaging
version: 1.0
baseUri: /mobile/custom/synapseStaging
protocols: [HTTPS]
mediaType: "application/json"
/user:
  /info:
    /{user_id}:
      uriParameters:
        user_id:
          displayName: user_id
          type: string
          required: true
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {"data": [{"home_long": -122.165347, "home_lat": 37.428074, "user_id": 0}]}

    /all:
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {"data": [{"home_long": -122.165347, "home_lat": 37.428074, "user_id": 0}, {"home_long": -122.169144, "home_lat": 37.422618, "user_id": 1}, {"home_long": -122.181718, "home_lat": 37.422738, "user_id": 2}, {"home_long": -122.163222, "home_lat": 37.433813, "user_id": 3}, {"home_long": -122.161569, "home_lat": 37.422601, "user_id": 4}, {"home_long": -122.159703, "home_lat": 37.426895, "user_id": 5}, {"home_long": -122.178156, "home_lat": 37.426265, "user_id": 6}]}

/report:
  /add:
    post:
      body:
        application/json:
          example: |
            {}

      responses:
        201:
          body:
            application/json:
              example: |
                {}

  /info:
    /all:
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {"data": [{"category": "Road Closure", "event_id": 0, "location_long": -73.980381, "score": 13.0, "radius": 0.5, "location_lat": 40.719664}, {"category": "Food", "event_id": 1, "location_long": -74.014362, "score": 22.0, "radius": 0.3, "location_lat": 40.703233}, {"category": "Water", "event_id": 2, "location_long": -73.977589, "score": -1.0, "radius": 0.4, "location_lat": 40.7154}]}

    /{report_id}:
      uriParameters:
        report_id:
          displayName: report_id
          type: string
          required: true
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {"data": [{"category": "Road Closure", "event_id": 0, "location_long": -73.980381, "score": 13.0, "radius": 0.5, "location_lat": 40.719664}]}

/event:
  /info:
    /{event_id}:
      uriParameters:
        event_id:
          displayName: event_id
          type: string
          required: true
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {"data": [{"category": "Hospital", "event_id": 3, "location_long": -73.99890907999605, "score": 10.0, "radius": 0.0, "location_lat": 40.710305745630365}]}

    /all:
      get:
        responses:
          200:
            body:
              application/json:
                example: |
                  {"data": [{"category": "Road Closure", "event_id": 0, "location_long": -73.980381, "score": 13.0, "radius": 0.5, "location_lat": 40.719664}, {"category": "Food", "event_id": 1, "location_long": -74.014362, "score": 46.0, "radius": 0.3, "location_lat": 40.703233}, {"category": "Water", "event_id": 2, "location_long": -73.977589, "score": -1.0, "radius": 0.4, "location_lat": 40.7154}, {"category": "Hospital", "event_id": 3, "location_long": -73.99890907999605, "score": 10.0, "radius": 0.0, "location_lat": 40.710305745630365}]}
    /bounds:
      /{latSW}/{lonSW}/{latNE}/{lonNE}:
        uriParameters:
          latSW:
            displayName: latSW
            type: string
            required: true
          lonSW:
            displayName: lonSW
            type: string
            required: true
          latNE:
            displayName: latNE
            type: string
            required: true
          lonNE:
            displayName: lonNE
            type: string
            required: true
        get:
          responses:
            200:
              body:
                application/json:
                  example: |
                    {"data": [{"category": "Road Closure", "event_id": 0, "location_long": -73.980381, "score": 13.0, "radius": 0.5, "location_lat": 40.719664}, {"category": "Food", "event_id": 1, "location_long": -74.014362, "score": 46.0, "radius": 0.3, "location_lat": 40.703233}, {"category": "Water", "event_id": 2, "location_long": -73.977589, "score": -1.0, "radius": 0.4, "location_lat": 40.7154}, {"category": "Hospital", "event_id": 3, "location_long": -73.99890907999605, "score": 10.0, "radius": 0.0, "location_lat": 40.710305745630365}]}


  /verify:
    post:
      description: |
        Verify an event
      body:
        application/json:
          example: |
            {}

      responses:
        201:
          body:
            application/json:
              example: |
                {"event_id": 1, "new_score": 2}

  /dispute:
    post:
      description: |
        Dispute an event
      body:
        application/json:
          example: |
            {}
      responses:
        201:
          body:
            application/json:
              example: |
                {"event_id": 1, "new_score": 2}
